### ISSUE TITLE
openal32.dll not found

### ISSUE THREAD

**Issue by chtenb** [tomrijnbeek/Cireon.Audio#6]
Get an error  on windows 8:

```
Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'OpenTK.Audio.AudioContext' threw an exception. ---> System.TypeInitialization
Exception: The type initializer for 'OpenTK.Audio.AudioDeviceEnumerator' threw a
n exception. ---> System.DllNotFoundException: Unable to load DLL 'openal32.dll'
: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenTK.Audio.OpenAL.Alc.MakeContextCurrent(IntPtr context)
   at OpenTK.Audio.OpenAL.Alc.MakeContextCurrent(ContextHandle context)
   at OpenTK.Audio.AudioDeviceEnumerator..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Audio.AudioDeviceEnumerator.get_IsOpenALSupported()
   --- End of inner exception stack trace ---
   at OpenTK.Audio.AudioContext..ctor()
   at Cireon.Audio.AudioManager..ctor() in c:\Users\Chiel\Desktop\yatl\libs\Cire
on.Audio\src\Cireon.Audio\AudioManager.cs:line 116
   at yatl.MusicManager..ctor() in c:\Users\Chiel\Desktop\yatl\src\yatl\Music\Mu
sicManager.cs:line 61
   at yatl.YATLWindow.OnLoad(EventArgs e) in c:\Users\Chiel\Desktop\yatl\src\yat
l\YATLWindow.cs:line 44
   at amulware.Graphics.Program.Run(Double targetUpdatesPerSecond, Double target
DrawsPerSecond, Double maximumFrameTimeFactor) in c:\Users\Chiel\Desktop\yatl\li
bs\awgraphics\src\amulware.Graphics\Program.cs:line 192
   at yatl.Program.Main(String[] args) in c:\Users\Chiel\Desktop\yatl\src\yatl\P
rogram.cs:line 18
```

**Comment by chtenb** [comment]
Manually installing openal from e.g. http://openal.updatestar.com/ is a workaround, but including openal32.dll in this project could be considered.
